export const SET_HOT_KEYWRODS = "SET_HOT_KEYWRODS";
export const SET_SUGGEST_LIST = 'SET_SUGGEST_LIST';
export const SET_RESULT_SONGS_LIST = 'SET_RESULT_SONGS_LIST';
export const SET_ENTER_LOADING = 'SET_ENTER_LOADING'; 